language: java
before_install:
  - docker-compose up -d
  - cp src/main/resources/config.properties.example src/main/resources/config.properties
  - cp src/main/resources/application.properties.example src/main/resources/application.properties
  - chmod +x mvnw
  - mvn compile # compile java source file first, because the test file used those
  - mvn kotlin:test-compile # compile kotlin file
script:
  - mvn test -B -l=testlog.txt
after_script:
  - docker-compose down -v